import { Poppins } from "next/font/google";
import "./globals.css";
import { ThreeDProvider } from "./context/3DContext";
import { TwoDProvider } from "./context/2DContext";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"], 
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} kr-antialiased kr-bg-screen kr-reset-margin-padding`}>
        <TwoDProvider>
          <ThreeDProvider>
            {children}
          </ThreeDProvider>
        </TwoDProvider>
      </body>
    </html>
  );
}
